### PR TITLE
Fix wildcard support for $targetBranch

### PR DESCRIPTION
**Pull request by inikulshin**

### CODE REVIEW

**Comment by shayki5** [comment]
Hi @inikulshin, see my comment :)

**Comment by inikulshin** [comment]
> Hi @inikulshin, see my comment :)

I don't see any comments.

**Comment by shayki5** [comment]
@inikulshin 
image

**Comment by inikulshin** [comment]
Fixed.

Btw, what will happen if `$targetBranches.Contains($sourceBranch)` ?

**Comment by shayki5** [comment]
I guess it will fail when he will try to create a PR.

**Review by shayki5 — APPROVED** [review]

**Pull request merged**
