### PR TITLE
Fixed naming of delete sourcebranch parameter

### PR DESCRIPTION
**Pull request by Bene2205**
Fixed naming of delete sourcebranch parameter

### CODE REVIEW

**Comment by shayki5** [comment]
Hi @Bene2205!
Thank you for your contribution! 
Please see issue #80 - you fixed the typo inside the PowerShell code that it's great, but in the yam is still will be `deleteSourch`.
Do you have an idea to fix it there without break current yaml pipelines? (and without increase the task version to 2.0)

**Comment by Bene2205** [comment]
We could add it in addition. This would make the "deleteSourch" still available (maybe we can set this obsolete). And for newly created pipelines "deleteSource" can be used? 

```json
{
    "name": "deleteSourch",
    "type": "boolean",
    "label": "Delete Sourch Branch",
    "defaultValue": false,
    "required": false,
    "helpMarkDown": "If true, the source branch of the pull request will be deleted after completion.",
    "groupName": "completion",
    "visibleRule": "autoComplete=true"
  },
{
    "name": "deleteSource",
    "type": "boolean",
    "label": "Delete Sourch Branch",
    "defaultValue": false,
    "required": false,
    "helpMarkDown": "If true, the source branch of the pull request will be deleted after completion.",
    "groupName": "completion",
    "visibleRule": "autoComplete=true"
  },
```

**Comment by shayki5** [comment]
Hi, in that case in the UI will be 2 fields :/ maybe to change the `visibleRule` for the old one?

**Comment by karpis** [comment]
Just add the old name as an alias, like so:

```
{
    "name": "deleteSource",
    "aliases": [
        "deleteSourch"
    ],
    "type": "boolean",
    "label": "Delete Source Branch",
    "defaultValue": false,
    "required": false,
    "helpMarkDown": "If true, the source branch of the pull request will be deleted after completion.",
    "groupName": "completion",
    "visibleRule": "autoComplete=true"
  },
```

**Comment by shayki5** [comment]
Interesting! do you know what the `alias` does?

**Comment by karpis** [comment]
Allows you to have several names for the same task input. See https://github.com/microsoft/azure-pipelines-task-lib/blob/master/tasks.schema.json and https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/NuGetCommandV2/task.json

**Comment by shayki5** [comment]
Awesome! so can you fix the PR please?

**Review by shayki5 — APPROVED** [review]

**Comment by shayki5** [comment]
Thank you @karpis and @Bene2205! I merged the code and uploaded the new version :)

**Pull request merged**
