### PR TITLE
Verify source and target branches exist before making PR

### PR DESCRIPTION
**Pull request by ligz08**
Verify branches exist; if not, raise error and terminate early.

### CODE REVIEW

**Comment by shayki5** [comment]
Hi, thank you for the contribution! great idea!

**Review by shayki5 — APPROVED** [review]

**Comment by Neale-Forrest** [comment]
I think this might have broken something.  Using 1.2.360 it worked correctly.  as of version 1.2.363 it has stopped working.  and our repo names have not changed.
image
image

**Comment by ligz08** [comment]
Thanks @Neale-Forrest for catching this. Made another PR #175 to fix.

**Comment by shayki5** [comment]
@Neale-Forrest I merged the fix, can you test now please?

**Pull request merged**
